version: '3.4'

services:

  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
        - "5000:80" 

  db:
    image: mariadb:10.4.17
    container_name: db
    restart: always
    ports:
       - '3306:3306'
    environment:
       MYSQL_DATABASE: oneblinq
       MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

  pma:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db

  front:
    container_name: front
    build:
      context: ../Oneblinq-Front
      dockerfile: ../Oneblinq-Front/Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

volumes:
  dbdata:
